spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: ${MULTIPART_FILE_SIZE_THRESHOLD}
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  h2:
    console:
      enabled: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: false

server:
  oidc:
    email: ${OIDC_EMAIL}
    password: ${OIDC_PASSWORD}
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    name: ${ADMIN_NAME}
    onesignal-id: ${ADMIN_ONESIGNAL_ID}
  web:
    max-count-requests: ${MAX_COUNT_REQUESTS}
  zitadel:
    id: ${REGISTRATION_ID}
    client-id: ${ZITADEL_CLIENT_ID}
    client-secret: ${ZITADEL_CLIENT_SECRET}
    scope: ${ZITADEL_SCOPE}
    token-uri: ${ZITADEL_TOKEN_URI}
  jwt:
    token:
      signing:
        key: ${JWT_SIGNING_KEY}
  email:
    name: ${APP_EMAIL}
    host: smtp.yandex.ru
    password: ${APP_EMAIL_PASSWORD}
    port: 465
    protocol: smtps
    debug: false
    verification-code-length: ${VERIFICATION_CODE_LENGTH}
  web-client:
    time-response: ${FIXED_RESPONSE}
  integration:
    base-url: ${INTEGRATION_SERVICE_BASE_URL}
    video-storage:
      uri: ${VIDEO_STORAGE_URI}
      type: ${VIDEO_STORAGE_TYPE}
    notification-service:
      uri: ${NOTIFICATION_SERVICE_URI}
      message: ${NOTIFICATION_SERVICE_USER_MESSAGE}
    meditation-ai-path: ${INTEGRATION_MEDITATION_AI_PATH}
    fixed-rate-time: ${FIXED_RATE_TIME}
    fixed-update: ${FIXED_UPDATE}
    payment-service-path: ${INTEGRATION_PAYMENT_SERVICE_PATH}
  port: ${PORT}

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: false
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 60
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      convert-service:
        baseConfig: default

web-retry:
  max-attempts: 10
  backoff:
    min-delay: 50
    multiplier: 2
    max-delay: 10000