spring:
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# need to remove values when realize
server:
  jwt:
    token:
      signing:
        key: ${JWT_SIGNING_KEY}
  email:
    name: ${APP_EMAIL}
    host: smtp.yandex.ru
    password: ${APP_EMAIL_PASSWORD}
    port: 465
    protocol: smtps
    debug: false
    verification-code-length: 4
  port: ${PORT:8080}
