spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: ${MULTIPART_FILE_SIZE_THRESHOLD}
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  h2:
    console:
      enabled: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: false

server:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    name: ${ADMIN_NAME}
    onesignal-id: ${ADMIN_ONESIGNAL_ID}
  web:
    max-count-requests: ${MAX_COUNT_REQUESTS}
  jwt:
    token:
      signing:
        key: ${JWT_SIGNING_KEY}
  email:
    name: ${APP_EMAIL}
    host: smtp.yandex.ru
    password: ${APP_EMAIL_PASSWORD}
    port: 465
    protocol: smtps
    debug: false
    verification-code-length: ${VERIFICATION_CODE_LENGTH}
  keycloak:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    url: ${KEYCLOAK_URL}
    realm: ${KEYCLOAK_REALM}
  oauth:
    grand-type: "client_credentials"
  web-client:
    time-response: 15
  integration:
    base-url: ${INTEGRATION_SERVICE_BASE_URL}
    video-storage:
      uri: ${VIDEO_STORAGE_URI}
      type: ${VIDEO_STORAGE_TYPE}
      kinescope-uri: ${KINESCOPE_URI}
      upload-path: ${UPLOAD_PATH}
    notification-service:
      uri: ${NOTIFICATION_SERVICE_URI}
      message: ${NOTIFICATION_SERVICE_USER_MESSAGE}
    meditation-ai-path: ${INTEGRATION_MEDITATION_AI_PATH}
    fixed-rate-time: 60000
    fixed-update: 30000
    payment-service-path: ${INTEGRATION_PAYMENT_SERVICE_PATH}
  port: ${PORT}

