spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:aura_flow}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true

server:
  port: ${PORT:8080}
  jwt:
    token:
      signing:
        key: ${JWT_SIGNING_KEY}
  email:
    name: ${APP_EMAIL}
    host: smtp.yandex.ru
    password: ${APP_EMAIL_PASSWORD}
    port: 465
    protocol: smtps
    debug: false
    verification-code-length: 4
